language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "sonar-intellij-plugin"

jdk:
  - openjdk8

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
